

//#define LOG_LEVEL_CONSOLE  LOG_NOLOG
//#define LOG_LEVEL_CONSOLE  LOG_WARNINGS
//#define LOG_LEVEL_CONSOLE  LOG_ERRORS
//#define LOG_LEVEL_CONSOLE  LOG_ALL

//#define LOG_LEVEL_FILE  LOG_NOLOG
//#define LOG_LEVEL_FILE  LOG_WARNINGS
//#define LOG_LEVEL_FILE  LOG_ERRORS
//#define LOG_LEVEL_FILE  LOG_ALL

//#define SETTINGS_UPDATE_INTERVAL 20000